% cheater script to clear all non-structured plotting-assistive vars

clear ans bar_condlabel bar_data bar_data_se bar_glabel bar_h bar_title ...
    bw_colormap bw_xlabel bw_ylabel cents chan cond cond_colors di_bins ...
    di_bins_diff ero_diff_limits ero_plot_data ero_plot_data_std ...
    ero_topo_scale erp_diff_limits erp_plot_data erp_plot_data_std ...
    erp_topo_data erp_topo_scale error_sides f_end f_indiv f_start ...
    f_indiv_hz fig figdum freq freq_range gridstatus ...
    group group_dummy h h_line intensity_data ispc_data ispc_diff_limits ...
    ispc_plot_data ispc_topo_scale itc_axes itc_diff_limits itc_freqcorr ...
    itc_freqcorr_data itc_histdata itc_histdata_se itc_plot_data ...
    itc_scatterdata_x itc_scatterdata_y itc_topo_scale legend_type nels ...
    p p_phase p_tfwin phase_axes phase_data phase_diff_limits ...
    phase_plot_data phase_topo_scale scatter_h scatterdata_x ...
    scatterdata_y sp splot stat subplot_dummy t_end t_start topo_data ...
    v width win wind_title z overtitle sp_columnlabel sp_rowlabel ...
    subplot_dims x_plotlabel y_plotlabel ero_yax ero_axes ero_axes_diff ...
    gdum ranova_data ranova_table ero_scatterdata_x ero_scatterdata_y ...
    f itc_axes_diff xi coh_scatterdata_x coh_scatterdata_y coh_tf_data ...
    erpcoh_scatterdata_x erpcoh_scatterdata_y scatter_limits pair ...
    cbar_ticks chan_coh_measure chan_coh_stat chosen_chan direction ...
    dummydata line_limit line_limit_diff linecolor linescale ...
    paircoh_color paircoh_for_linecolor statsgroup trial_coh_measure ...
    x y coh_linescale_mat coh_linescale coh_linescale_diff linesize ...
    seed seed_label seed_pairs