clear a b distance error estimates_mat f_end f_start fitdata freq_range ...
    model model_line n_params p_dists params_mat plotdata s s_inds ...
    subplot_dummy t_end t_start timeregion ans chan_cohlims chan_cohranges ...
    coh_plotmeans cohlim_mat cohmax_mat cohmean_mat cohmin_mat cond ...
    dcm_h error estimates f freqregion group inds lookup overtitle ...
    p_dists_sorted pair pair_g pair_type_inds pair_types params ptype ...
    sstyles timeregion error_mat g_lab hyp hyp_colors hyps plot_hypinds