function [pairs, region_inds, region_indlbls] = coh_pairgui_region(coords_file)

geometry = { [3 1] [3 1] [3.33 1.66 1 1.5] ...
            };

uilist = {  { 'Style', 'text', 'string', 'Region relation (inter, intra, or both)' }, ...
            { 'Style', 'edit', 'string', 'inter' } ...
            ...
            { 'Style', 'text', 'string', 'Regions (frontal,central,parietal,occipital,lefttemporal,righttemporal are supported, use default as template)', 'horizontalalignment' , 'right' }, ...
            { 'Style', 'edit', 'string', '{''frontal'',''parietal'',''occipital''}' } ...
            ...
            { 'Style', 'text', 'string', 'Make sparser (reduce total pairs)?' }, ...
            { 'Style', 'checkbox', 'Value', 1, 'string', '', 'horizontalalignment', 'right'}, ...
            {}, ...
            {}, ...
            };

results=inputgui(geometry,uilist,'help coh_pairgui_region;','Generate pairs based on regions');

relation=results{1};
regions=eval(results{2});
sparse_logic=logical(results{3});

[pairs, region_inds, region_indlbls]= ...
    determine_regional_pairs(coords_file,relation,regions,sparse_logic);

end