function pairs = coh_pairgui_determine(coords_file)

geometry = { [3.33 1.66 1 1.5] [2 1 1.5] [2 1 1.5] [2 1 1.5] [3.33 1.66 1 1.5] ...
            };

uilist = {  { 'Style', 'text', 'string', 'Include outer electrodes?' }, ...
            { 'Style', 'checkbox', 'Value', 0, 'string', '', 'horizontalalignment', 'right'}, ...
            {}, ...
            {}, ...
            ...
            { 'Style', 'text', 'string', 'Distance range between electrodes [lower upper] (in cm)', 'horizontalalignment' , 'right' }, ...
            { 'Style', 'edit', 'string', '[6 12]' } ...
            { 'Style', 'text', 'string', ''  }, ...
            ...
            { 'Style', 'text', 'string', 'Pair orientation (all, ap, lr, aplr, or diag)', 'horizontalalignment' , 'right' }, ...
            { 'Style', 'edit', 'string', 'aplr' } ...
            { 'Style', 'text', 'string', ''  }, ...
            ...
            { 'Style', 'text', 'string', 'Max pair membership per channel', 'horizontalalignment' , 'right' }, ...
            { 'Style', 'edit', 'string', '3' } ...
            { 'Style', 'text', 'string', ''  }, ...
            ...
            { 'Style', 'text', 'string', 'Plot output?' }, ...
            { 'Style', 'checkbox', 'Value', 1, 'string', '', 'horizontalalignment', 'right'}, ...
            {}, ...
            {}, ...
            };

results=inputgui(geometry,uilist,'help coh_pairgui_determine;','Set parameters for pair determination');

exclude=~logical(results{1});
distance=eval(results{2});
orientation=results{3};
edges=eval(results{4});
do_plot=logical(results{5});

pairs=determine_distant_pairs(coords_file,exclude,distance,orientation,edges,do_plot);

end