function [startover, plot_bool, filter_bool, restore_bool]=coh_pairgui_check(pairs)

n_pairs=size(pairs,1);

geometry = { [3 1] [3 1] [3 1] [3 1] ...
            };

uilist = {  { 'Style', 'text', 'string', ['Your choice resulted in ',num2str(n_pairs),' pairs. To accept as final, check the box (overwrites filtering & restoration).'], 'horizontalalignment', 'right' }, ...
            { 'Style', 'checkbox', 'Value', 0, 'string', '', 'horizontalalignment', 'right'}, ...
            ...
            { 'Style', 'text', 'string', 'Plot? (check to plot)', 'horizontalalignment', 'right' }, ...
            { 'Style', 'checkbox', 'Value', 1, 'string', '', 'horizontalalignment', 'right'}, ...
            ...
            { 'Style', 'text', 'string', 'Filter by distance, angle, etc.? (check to filter)', 'horizontalalignment', 'right' }, ...
            { 'Style', 'checkbox', 'Value', 1, 'string', '', 'horizontalalignment', 'right'}, ...
            ...
            { 'Style', 'text', 'string', 'Restore previous set of pairs? (check to restore, overwrites filtering)', 'horizontalalignment', 'right' }, ...
            { 'Style', 'checkbox', 'Value', 0, 'string', '', 'horizontalalignment', 'right'}, ...
            };

results=inputgui(geometry,uilist,'help coh_pairgui_check;','Check pairs');

startover = ~logical(results{1});
plot_bool = logical(results{2});
filter_bool = logical(results{3});
restore_bool= logical(results{4});

end