function [pairs, seed_inds, seed_indlbls] = coh_pairgui_seed

commandload = [ '[filename, filepath] = uigetfile(''*'', ''Select a coordinates file'');' ...
                    'if filename(1) ~=0,' ...
                    '   set(findobj(''parent'', gcbf, ''tag'', tagtest), ''string'', [ filepath filename ]);' ...
                    'end;' ...
                    'clear filename filepath tagtest;' ];

geometry = { [2 1 1.5] [2 1 1.5] ...
            };

uilist = {  { 'Style', 'text', 'string', 'Channel locations file for sub-set of channels to cohere with seed', 'horizontalalignment', 'right' }, ...
            { 'Style', 'edit', 'string', '/export/home/mike/matlab/origin/coords/31chans_ns.mat', 'horizontalalignment', 'left', 'tag',  'Mapfile' }, ...
            { 'Style', 'pushbutton', 'string', 'Browse', 'callback', [ 'tagtest = ''Mapfile'';' commandload ] }, ...
            ...
            { 'Style', 'text', 'string', 'Seed channels as indices ( [7 8] ) or channel names (format by example below)', ...
            'horizontalalignment' , 'right' }, ...
            { 'Style', 'edit', 'string', '{''F4'', ''F3'', ''P3'', ''P4''}' } ...
            { 'Style', 'text', 'string', ''  }, ...
            };

results=inputgui(geometry,uilist,'help coh_pairgui_seed;','Set seeds for seed coherence');

coords_file=results{1};
seed_electrodes=eval(results{2});

[pairs, seed_inds, seed_indlbls]=pair_with_all_others(coords_file, seed_electrodes);

end