clear a cb_width do_film ero_cmap ero_cmap_diff ero_topo_data f_end_hz ...
    f_start_hz film film_dum h2 itc_cmap itc_cmap_diff itc_topo_data ...
    n_colors n_ticks outfile spacefactor subplot_key t_end_ms t_start_ms ...
    timeframe w writerObj